ModulePlayer/Models/Module.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ModulePlayer.Models
{
    public class Module
    {
        protected Module()
        {
            
        }

        public Module(string title, string url, string packagetype)
        {
            Id = Guid.NewGuid();
            Title = title;
            Url = url;
            Packagetype = packagetype;
            TrackingData = new TrackingData("0",false, "", "");
            CompletedTimes = 0;
            RestartedTimes = 0;
        }

        public Guid Id { get; set; }
        public string Title { get; set; }
        public string Url { get; set; }
        public string Packagetype { get; set; }
        public TrackingData TrackingData { get; set; }
        public int CompletedTimes { get; set; }
        public int RestartedTimes { get; set; }
    }
}

ModulePlayer/Controllers/ModulesController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using MimeKit;
using ModulePlayer.Azure;
using ModulePlayer.DataAccess;
using ModulePlayer.Models;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace ModulePlayer.Controllers
{
    public class ModulesController : Controller
    {
        private readonly ApplicationDbContext _ctx;
        private readonly IFileDownloader _fileDownloader;

        public ModulesController(ApplicationDbContext ctx, IFileDownloader fileDownloader)
        {
            _ctx = ctx;
            _fileDownloader = fileDownloader;
        }

        public async Task<IActionResult> Index()
        {
            var modules = await _ctx.Modules.ToListAsync();
            return View(modules);
        }

        [HttpGet("module/{id}")]
        public async Task<IActionResult> Module(Guid id)
        {
            var module = await _ctx.Modules.Where(m => m.Id == id).Include(m => m.TrackingData).FirstOrDefaultAsync();
            return View(module);
        }

        [HttpGet("module/playcourse/{*filePath:regex(\\S{{1,}})}")]
        public async Task<IActionResult> GetFileAsync(string filePath)
        {
            var fileBytes = await _fileDownloader.DownloadFileBytes(filePath);
            if (fileBytes == null)
            {
                return StatusCode(StatusCodes.Status404NotFound);
            }

            return File(fileBytes, MimeTypes.GetMimeType(filePath));
        }
    }
}

ModulePlayer/Controllers/TinCanController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using ModulePlayer.DataAccess;
using ModulePlayer.Models;
using Newtonsoft.Json;

namespace ModulePlayer.Controllers
{
    [ApiController]
    public class TinCanController : ControllerBase
    {
        private readonly ApplicationDbContext _ctx;

        public TinCanController(ApplicationDbContext ctx)
        {
            _ctx = ctx;
        }
        
        [HttpGet("tincan/activities/state")]
        public async Task<IActionResult> TinCan([FromQuery] string stateId, [FromQuery] string activityId, [FromQuery] Guid registration)
        {
            var module = await _ctx.Modules.Include(m => m.TrackingData).FirstOrDefaultAsync(m => m.Id == registration);
            if (stateId == "bookmark")
            {
                return Ok(module.TrackingData.Location);
            }

            if (stateId == "suspend_data")
            {
                return Ok(module.TrackingData.SuspendData);
            }
            return new OkResult();
        }

        [HttpGet("reset/{id}")]
        public async Task<IActionResult> ResetModule(Guid id)
        {
            var module = await _ctx.Modules.Where(m => m.Id == id).Include(m => m.TrackingData).FirstOrDefaultAsync();
            module.TrackingData.Complete = false;
            module.TrackingData.Location = null;
            module.TrackingData.SuspendData = null;
            module.TrackingData.Progress = null;
            module.RestartedTimes = module.RestartedTimes + 1;
            
            await _ctx.SaveChangesAsync();
            return RedirectToAction("module", "Modules", new { @id = module.Id });
        }
        
        [HttpPut("tincan/activities/state")]
        public async Task<IActionResult> TinCan3([FromQuery] string stateId, [FromQuery] string activityId, [FromQuery] Guid registration, [FromBody] byte[] payload)
        {
            string value = System.Text.Encoding.UTF8.GetString(payload);

            var module = await _ctx.Modules.Include(m => m.TrackingData)
                .FirstOrDefaultAsync(m => m.Id == registration);

            if (stateId == "bookmark")
            {
                module.TrackingData.Location = value;
            }

            if (stateId == "suspend_data")
            {
                module.TrackingData.SuspendData = value;
            }

            await _ctx.SaveChangesAsync();
            return new OkResult();
        }

        [HttpPut("tincan/statements")]
        public async Task<IActionResult> TinCan2([FromQuery] string statementId, [FromBody] object data)
        {
            var dataString = JsonConvert.DeserializeObject<DataString>(data.ToString());
            var module = await _ctx.Modules.Include(m => m.TrackingData)
                .Where(m => m.Id == Guid.Parse(dataString.Context.Registration))
                .FirstOrDefaultAsync();

            if (dataString.Result.Completion != null)
            {
                module.TrackingData.Complete = bool.Parse(dataString.Result.Completion);
                if (bool.Parse(dataString.Result.Completion))
                {
                    module.CompletedTimes = module.CompletedTimes + 1;
                }
            }
            if (dataString.Result.Extensions != null)
            {
                module.TrackingData.Progress = dataString.Result.Extensions.Progress;
            }
            await _ctx.SaveChangesAsync();

            return Ok(dataString);
        }
    }
}

ModulePlayer/Views/Modules/Index.cshtml
@model IEnumerable<Module>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div class="row">
    <div class="col-12">
        @foreach (var module in @Model)
        {
            <a href="Module/@module.Id" target="_blank"><p>@module.Title</p></a>
        }
    </div>
</div>

ModulePlayer/Views/Modules/Module.cshtml
@using System.Text.Encodings.Web
@model Module
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<script src="~/RusticiSoftware-TinCanJS-0.50.0-0-g8733f14/RusticiSoftware-TinCanJS-8733f14/build/tincan.js"></script>
<script>
    var API = (function () {
        var data = {
            //"cmi.core.student_id": "5873D3FB-EA85-4385-E55B-08D8C3BBB6E7",
            //"cmi.learner_name": "Joe Bloggs",
            //"cmi.core.student_name": "Joe Bloggs",
            //"cmi.location": "",
            //"cmi.core.lesson_location": "index.html#/lessons/y3iqZjwZMpoL_ZI0SnktKjK-WYBolENv",
            //"cmi.completion_status": "incomplete",
            "cmi.core.lesson_status": "not attempted",
            //"cmi.suspend_data": null,
            //"cmi.success_status": "",
            //"cmi.score.raw": 0,
            //"cmi.core.score.raw": 0,
            //"cmi.score.min": 0,
            //"cmi.score.max": 0,
            //"cmi.score.scaled": 0,
            "initialised": false
        };
        return {
            Initialize: function () {
                console.log("API - init");
                data["initialised"] = true;
                return "true";
            },
            LMSInitialize: function () {
                console.log("API - init");
                data["initialised"] = true;
                return "true";
            },
            Commit: function () {
                console.log("%cAPI Commit", " background: white; border: 3px solid orange; color: orange;-size: 25px;margin: 20px; padding: 10px;");
                if (data["initialised"]) {
                    console.log(data);
                }


                return "true";
            },
            LMSCommit: function () {
                console.log("%cAPI Commit", " background: white; border: 3px solid orange; color: orange;-size: 25px;margin: 20px; padding: 10px;");
                if (data["initialised"]) {
                    console.log(data);
                }


                return "true";
            },
            Finish: function () {
                console.log("API - finish");
                return "true";
            },
            LMSFinish: function () {
                console.log("API - finish");
                return "true";
            },
            Terminate: function () {
                console.log("API - terminate");
                return "true";
            },
            LMSTerminate: function () {
                console.log("API - terminate");
                return "true";
            },
            GetValue: function (model) {
                console.log("%cGet value", " background: white; border: 3px solid red; color: red;-size: 25px;margin: 20px; padding: 10px;");
                console.log(model);
                console.log(data[model]);
                return data[model] || "";
            },
            LMSGetValue: function (model) {
                console.log("%cGet value", " background: white; border: 3px solid red; color: red;-size: 25px;margin: 20px; padding: 10px;");
                console.log(model);
                console.log(data[model]);
                return data[model] || "";
            },
            SetValue: function (model, value) {
                console.log("%cSet value", " background: white; border: 3px solid green; color: green;-size: 25px;margin: 20px; padding: 10px;");
                console.log(model, value);
                data[model] = value;
                return "true";
            },
            LMSSetValue: function (model, value) {
                console.log("%cSet value ", " background: white; border: 3px solid green; color: green;-size: 25px;margin: 20px; padding: 10px;");
                console.log(model, value);
                data[model] = value;
                return "true";
            },
            GetLastError: function () {
                return "0";
            },
            LMSGetLastError: function () {
                return "0";
            },
            GetErrorString: function (errorCode) {
                return "No error";
            },
            LMSGetErrorString: function (errorCode) {
                return "No error";
            },
            GetDiagnostic: function (errorCode) {
                return "No error";
            },
            LMSGetDiagnostic: function (errorCode) {
                return "No error";
            }
        };
    })();
    var API_1484_11 = API;
</script>

@{

    var encoder = UrlEncoder.Create();

    var query = "?endpoint=https://localhost:44340/tincan" +
                "&auth=Basic OjFjMGY4NTYxNzUwOGI4YWY0NjFkNzU5MWUxMzE1ZGQ1" +
                "&actor={\"name\": [\"First Last\"], \"mbox\": [\"mailto: firstlast@mycompany.com\"]}" +
                $"&activity_id={@Model.Id}" +
                $"&registration={@Model.Id}";
    var url = Model.Url;
    if (Model.Packagetype == "xApi" || Model.Packagetype == "cmi5")
    {
        url = @Model.Url + query;
    }

}

<div class="container-fluid">
    <div class="row mb-5">
        <div class="col-4">
            <p>Progress: @Model.TrackingData.Progress%</p>
        </div>
        <div class="col-4">
            <p>Is Complete: @Model.TrackingData.Complete.ToString()</p>
        </div>
        <div class="col-4">
            <p>Completed times: @Model.CompletedTimes</p>
        </div>
        <div class="col-4">
            <p>Restarted times: @Model.RestartedTimes</p>
        </div>
        <div class="col-4">
            <a asp-controller="TinCan" asp-action="ResetModule" asp-route-id="@Model.Id">
            <button class="btn btn-danger">Reset Progress</button>
            </a>
        </div>
    </div>
    <div class="row">
        <div class="col-12" style="height: 750px">
            <iframe style="width: 100%; height: 100%;" src="@url"></iframe>
        </div>
    </div>
</div>